VERSION --global-cache 0.7


# GRADLE_GET_MOUNT_CACHE sets the following entries in the calling environment:
# EARTH_GRADLE_USER_HOME_CACHE: Code of the mount cache for the gradle home.
# EARTH_GRADLE_PROJECT_CACHE: Code of the mount cache for the .gradle folder.
# Example:
#   DO gradle+GRADLE_GET_MOUNT_CACHE
#   RUN --mount=$EARTH_GRADLE_USER_HOME_CACHE --mount=$EARTH_GRADLE_PROJECT_CACHE gradle --no-daemon build
# Arguments:
#   - cache_prefix: To be used in both caches. By default: ${EARTH_TARGET_PROJECT_NO_TAG}#${OS_RELEASE}#earthly-gradle-cache
GRADLE_GET_MOUNT_CACHE:
    COMMAND
    ARG EARTH_TARGET_PROJECT_NO_TAG
    ARG cache_prefix = "${EARTH_TARGET_PROJECT_NO_TAG}#earthly-gradle-cache"
    IF [ "$GRADLE_USER_HOME" = "" ]
        ENV GRADLE_USER_HOME="$HOME/.gradle"
    END
    ENV EARTH_GRADLE_CACHE_PREFIX=$cache_prefix
    ENV EARTH_GRADLE_USER_HOME_CACHE="type=cache,mode=0777,id=$cache_prefix,sharing=shared,target=$GRADLE_USER_HOME"
    ENV EARTH_GRADLE_PROJECT_CACHE="type=cache,mode=0777,id=${cache_prefix}#project,sharing=shared,target=.gradle"
